/* Links externos */

export const document = [
    { url: 'https://www.w3schools.com/', texto: 'W3Schools.com' },
    { url: 'https://developer.mozilla.org/es/', texto: 'Mozilla Developer Network' },
    { url: 'https://desarrolloweb.com/', texto: 'Desarrolloweb.com' },
    { url: 'https://nodejs.org/es/docs', texto: 'Node JS' },
    { url: 'https://expressjs.com/es/', texto: 'Express JS'},
    { url: 'https://sequelize.org/docs/v6/', texto: 'Sequelize' },
    { url: 'https://www.mongodb.com/es', texto: 'MongoDB' },
    { url: 'https://www.postgresql.org/docs/current/index.html', texto: 'PostgreSQL' },
    { url: 'https://docs.npmjs.com/', texto: 'NPM JS' },
    { url: 'https://webpack.js.org/', texto: 'Webpack JS' },
    { url: 'https://www.jetbrains.com/help/idea/remote-development-overview.html', texto: 'Remote Development Oveview *' },
    { url: 'https://www.bigocheatsheet.com/', texto: 'Big O' },
    { url: 'https://www.atlassian.com/es/agile/scrum', texto: 'Scrum | Metodologías ágiles' },
    { url: 'https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf', texto: 'VSC shortcuts'}
];
export const tools = [
    { url: 'https://chat.openai.com/', texto: 'Chat-GPT' },
    { url: 'https://jsonplaceholder.typicode.com/', texto: 'JSON Placeholder' },
    { url: 'https://www.postman.com/', texto: 'Postman' },
    { url: 'https://insomnia.rest/', texto: 'Insomnia' },
    { url: 'https://fontawesome.com/', texto: 'Font Awesome' },
    { url: 'https://boxicons.com/', texto: 'Box Icons' },
    { url: 'https://react-icons.github.io/react-icons/', texto: 'React Icons' },
    { url: 'https://lenguajehtml.com/', texto: 'Lenguaje HTML' },
    { url: 'https://www.figma.com/', texto: 'Figma'},
    { url: 'https://replit.com/', texto: 'Replit' },
    { url: 'https://convertio.co/es/', texto: 'Convertio'},
    { url: 'https://www.pdfescape.com/', texto: 'PDF Escape'},
    { url: 'https://onecompiler.com/', texto: 'One Compiler'},
    { url: 'https://www.hostinger.com/', texto: 'Hostinger'},
    { url: 'https://www.netlify.com/', texto: 'Netlify'},
];
export const frameworks = [
    { url: 'https://es.react.dev/', texto: 'React' },
    { url: 'https://redux.js.org/', texto: 'Redux' },
    { url: 'https://nextjs.org/', texto: 'NextJS' },
    { url: 'https://www.docker.com/', texto: 'Docker' },
];
export const estilos = [
    { url: 'https://tailwindcss.com/', texto: 'Tailwind' },
    { url: 'https://getbootstrap.com/', texto: 'Bootstrap' },
    { url: 'https://lesscss.org/', texto: 'Less' },
    { url: 'https://sass-lang.com/', texto: 'Sass' },
    { url: 'https://cssbuttons.app/', texto: 'CSS Buttons' },
    { url: 'https://css-tricks.com/', texto: 'CSS Tricks' },
    { url: 'https://colorbox.io/', texto: 'Color Box' },
    { url: 'https://colorhunt.co/', texto: 'Color Hunt' },
    { url: 'https://flatuicolors.com/', texto: 'Flat UI Colors' },
    { url: 'https://copy-paste-css.com/', texto: 'Copy-Paste CSS' },
    { url: 'https://palettte.app/', texto: 'Palette' },
    { url: 'https://cssgenerator.org/', texto: 'CSS Generator' },
    { url: 'https://necolas.github.io/normalize.css/', texto: 'Normalize' },
    { url: 'https://www.browserstack.com/guide/what-are-css-and-media-query-breakpoints', texto: 'Media Query Breakpoints' },
    { url: 'https://necolas.github.io/normalize.css/', texto: 'Normalize' },
];
export const learning = [
    { url: 'https://codingpotions.com/', texto: 'Coding Potions' },
    { url: 'https://supermarkupworld.com/', texto: 'Super Markup World' },
    { url: 'https://flexboxfroggy.com/#es', texto: 'FlexBox Froggy' },
    { url: 'http://www.flexboxdefense.com/', texto: 'FlexBox Defense' },
    { url: 'https://flukeout.github.io/', texto: 'Fluke out' },
    { url: 'https://cssbattle.dev/', texto:'CSS Battle' },
    { url: 'https://tutorialmarkdown.com/', texto: 'Tutorial Mark Down' },
    { url: 'https://www.thepunctuationguide.com/index.html', texto: 'The Punctuation Guide'},
    { url: 'https://www.tutorialspoint.com/index.htm', texto: 'Tutorials Point' },
    { url: 'https://www.typescripttutorial.net/', texto: 'TypeScript Tutorial' },
    { url: 'https://www.hackerrank.com/', texto: 'HackerRank' },
    { url: 'https://leetcode.com/', texto: 'Leet Code' },
    { url: 'https://exercism.org/', texto: 'Exercism' },
    { url: 'https://adventjs.dev/es', texto: 'Advent JS' },
    { url: 'https://www.codewars.com/', texto: 'Code Wars' },
    { url: 'https://levelup.video/', texto: 'Level Up Tutorials' },
    { url: 'https://www.codecademy.com/', texto: 'Code Academy' },
    { url: 'https://www.academlo.com/', texto: 'Academlo' },
    { url: 'https://laravelers.com/', texto: 'Laravelers' },
    { url: 'https://www.soyhenry.com/', texto: 'Soy Henry' },
];
export const stuff = [
    { url: 'https://www.humblebundle.com/', texto: 'Humble Bundle'},
    { url: 'https://manz.dev/', texto: 'Manz Dev'},
    { url: 'https://midu.dev/', texto: 'Midu Dev'},
    { url: 'https://moure.dev/', texto: 'Moure Dev'},
];
export const apis = [
    { url: 'https://rickandmortyapi.com/', texto: 'Rick & Morty API'},
    { url: 'https://superheroapi.com/', texto: 'Super Hero API'},
    { url: 'https://swapi.dev/', texto: 'Star Wars API'},
    { url: 'https://pokeapi.co/', texto: 'Pokemon API'},
]